apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: http-echo
spec:
  template:
    metadata:
      # This is the name of our new "Revision," it must follow the convention {service-name}-{revision-name}
      name: http-echo-v1
    spec:
      containers:
        - image: jxlwqq/http-echo
          ports:
            - containerPort: 8080
          args:
            - "--text=v1"