apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-web-ingress
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hello-web-svc
                port:
                  number: 80
  ingressClassName: nginx