apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: http-echo
spec:
  template:
    metadata:
      name: http-echo-v2
    spec:
      containers:
        - image: jxlwqq/http-echo
          ports:
            - containerPort: 8080
          args:
            - "--text=v2"
  traffic:
    - latestRevision: true
      percent: 50
    - revisionName: http-echo-v1
      percent: 50