apiVersion: v1
kind: Service
metadata:
  name: fileserver-svc
  namespace: default
  labels:
    app: fileserver
spec:
  selector:
    app: fileserver
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP