apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator
  labels:
    app: calculator
spec:
  selector:
    matchLabels:
      app: calculator
  template:
    metadata:
      labels:
        app: calculator
    spec:
      containers:
        - name: calculator
          image: jxlwqq/calculator
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: calculator-svc
  labels:
    app: calculator
spec:
  selector:
    app: calculator
  ports:
    - port: 50051
      targetPort: 50051