kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: guestbook
  labels:
    app: guestbook
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
