kind: Deployment
apiVersion: apps/v1
metadata:
  name: laravel-deployment
  labels:
    app: laravel
spec:
  selector:
    matchLabels:
      app: laravel
  template:
    metadata:
      name: laravel
      labels:
        app: laravel
    spec:
      containers:
        - name: laravel
          image: jxlwqq/laravel-kubernetes-demo
          env:
            - name: DB_HOST
              value: mysql-service
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-password
                  key: MYSQL_ROOT_PASSWORD
            - name: REDIS_HOST
              value: redis-service
          envFrom:
            - configMapRef:
                name: laravel-env
          ports:
            - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: laravel-service
  labels:
    app: laravel
spec:
  selector:
    app: laravel
  ports:
    - port: 80
      targetPort: 80
