apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: nginx-virtual-service
spec:
  gateways:
    - nginx-gateway
  hosts:
    - "*"
  http:
    - route:
        - destination:
            host: nginx-svc
      fault:
        delay:
          percentage:
            value: 100
          fixedDelay: 5s
